add readme, tweak run-test

diff --git a/bin/run-test b/bin/run-test
--- a/bin/run-test
+++ b/bin/run-test
@@ -1,18 +1,29 @@
 #!/bin/bash
 
-if [ -z "${1}" ]; then
-  echo "Usage: run-test BRANCHNAME"
+if [ -z "${1}" ] || [ -z "${2}" ]; then
+  echo "Usage: run-test BRANCHNAME /path/to/cloud.conf"
   exit 1
 else
   TOP=$(git rev-parse --show-toplevel)
   BRANCHNAME=$1
   TESTBRANCHNAME=$1-$(date +%y%m%d-%H%M.%S)
+  CLOUDCONF=$2
   echo "Using branch name: ${BRANCHNAME}"
   echo "Using test branch name: ${TESTBRANCHNAME}"
+  echo "Using cloud.conf: ${CLOUDCONF}"
+  if [[ "${BRANCHNAME}" == "master" ]]; then
+    echo "NEVER CHANGE THE 'master' BRANCH"
+    exit 1
+  fi
   if ! git checkout -b ${TESTBRANCHNAME} ${BRANCHNAME}; then
     exit 1
   fi
   MESSAGE="Tested ${BRANCHNAME} in ${TESTBRANCHNAME} at $(date)"
+  if [ ! -e ${CLOUDCONF} ]; then
+    echo "Failed to find cloud.conf: ${CLOUDCONF}"
+    exit 1
+  fi
+  cp -fv ${CLOUDCONF} ${TOP}/root/cloud.conf
   if $TOP/bin/setup-chroot.sh root/tests/test.py | tee logs/stdout; then
     MESSAGE="${MESSAGE}\n\tSUCCEEDED\n\n"
   else
